### ISSUE TITLE
systemd v254 Behaviour of sandboxing options for the per-user service manager units has changed

### ISSUE THREAD

**Issue by L2501** [danstiner/rust-u2f#116]
in systemd 254 Behaviour of sandboxing options for the per-user service manager units has changed. They now imply PrivateUsers=yes see https://github.com/systemd/systemd/releases/tag/v254
it will be enabled for rust-u2f due to 
https://github.com/danstiner/rust-u2f/blob/da1a256e804395588c21c0dd9891310506746e7a/linux/user-daemon/softu2f.service#L8
this makes the root check fail https://github.com/danstiner/rust-u2f/blob/da1a256e804395588c21c0dd9891310506746e7a/linux/user-daemon/src/main.rs#L131

**Comment by danstiner** [comment]
Thanks for the report, fixed in master branch with 121a81db2a1b412be5723e22081578b074d5f7ea
