### ISSUE TITLE
No match for argument: softu2f

### ISSUE THREAD

**Issue by ThHareau** [danstiner/rust-u2f#26]
Under Fedora 28, the softu2f package cannot be found by dnf (after running the `script.rpm.sh`). 

```
$ sudo dnf install softu2f
Last metadata expiration check: 0:04:01 ago on Tue Jul 10 10:49:59 2018.
No match for argument: softu2f
Error: Unable to find a match
```

Please let me know if you need further details.

**Comment by danstiner** [comment]
I actually hadn't published a build for Fedora 28 yet, try now!

**Comment by ThHareau** [comment]
Yeah it works ;) Thanks a lot!

**Comment by danstiner** [comment]
Awesome! Let me know if you run into any problems, I've been waiting to see what comes out of WebAuthN before spending much more time on this project, but I'm always happy to hear feedback.

**Comment by ThHareau** [comment]
So far it works well, I just had difficulties to start the daemon (it stayed dead). Restarting the computer worked. I'll let you know
