### ISSUE TITLE
E: Unable to locate package softu2f

### ISSUE THREAD

**Issue by rcpao** [danstiner/rust-u2f#28]
```
from README.md:
Ubuntu Installation
$ sudo apt install -y curl
$ curl -s https://packagecloud.io/install/repositories/danstiner/softu2f/script.deb.sh | sudo bash
$ sudo  apt install -y softu2f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**E: Unable to locate package softu2f**

$ cat /etc/apt/sources.list.d/danstiner_softu2f.list 
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/danstiner/softu2f

deb https://packagecloud.io/danstiner/softu2f/ubuntu/ bionic main
deb-src https://packagecloud.io/danstiner/softu2f/ubuntu/ bionic main

**https://packagecloud.io/danstiner/softu2f/ubuntu/ does not exist: "The page you were looking for doesn't exist."**
```

**Comment by phuongvu0203** [comment]
I get the same issue. Is there anyone knows the exact problem?

**Comment by rcpao** [comment]
Firefox can show https://packagecloud.io/danstiner/softu2f no problem.
However, https://packagecloud.io/danstiner/softu2f/ubuntu (from /etc/apt/sources.list.d/danstiner_softu2f.list) does not exist.

WORKAROUND:

Skip the repository installation (by script or manual), and just download the .deb files for your version of Ubuntu.  I downloaded the [ubuntu/xenial] tagged files from https://packagecloud.io/app/danstiner/softu2f/search?dist=ubuntu%2Fxenial for my Ubuntu 18.04.1 (the xenial files work for bionic):

softu2f-user-daemon_0.2.0_amd64.deb
softu2f_0.1.0_all.deb
softu2f-system-daemon_0.2.0_amd64.deb
u2f-hidraw-policy_1.0.2-1_amd64.deb

I skipped the 0.1.0 versions of softu2f-system-daemon_0.1.0_amd64.deb and softu2f-user-daemon_0.1.0_amd64.deb assuming they were older versions of the 0.2.0 .deb files.

$ sudo dpkg -i softu2f-user-daemon_0.2.0_amd64.deb softu2f_0.1.0_all.deb softu2f-system-daemon_0.2.0_amd64.deb u2f-hidraw-policy_1.0.2-1_amd64.deb
$ systemctl --user start softu2f

Then start Chrome (Chromium does not work) and test with github.com.  Ubuntu 18.04.1 does not require a reboot.  It just works after the systemctl start is run and Chrome is started after.

**Comment by phuongvu0203** [comment]
That's cool, your suggestion works. I think the homepage (https://packagecloud.io) should change the installation steps.

**Comment by danstiner** [comment]
Ah, this is because I have not been publishing packages for newer versions of Ubuntu (bionic or cosmic). If people are still interested in playing around with this program I could build new packages.

**Comment by phuongvu0203** [comment]
> Ah, this is because I have not been publishing packages for newer versions of Ubuntu (bionic or cosmic). If people are still interested in playing around with this program I could build new packages.

Great to hear that. We'd appreciate if you could publish the newest version of Ubuntu. Thanks for reply.

**Comment by danstiner** [comment]
Pushed a new version for bionic, cosmic, and xenial. Let me know if it works!

**Comment by phuongvu0203** [comment]
> Pushed a new version for bionic, cosmic, and xenial. Let me know if it works!

It's working. Just do these steps for Ubuntu installation

> sudo apt install -y curl
> curl -s https://packagecloud.io/install/repositories/danstiner/softu2f/script.deb.sh | sudo bash
> sudo apt install -y softu2f
> systemctl --user start softu2f

Thank you

**Comment by danstiner** [comment]
Closing as it seems this has been fixed.

**Comment by silgon** [comment]
I just tested on `ubuntu 20.04`. I doesn't work for me.

![image](https://user-images.githubusercontent.com/901061/116080920-e8bf7280-a699-11eb-9294-60dd946ed236.png)

Any ideas?

**Comment by rcpao** [comment]
https://packagecloud.io/app/danstiner/softu2f/search?dist=ubuntu%2Ffocal
Packages for ubuntu/focal in danstiner / softu2f
No results!

**Comment by silgon** [comment]
Hey @rcpao and others who encounter this. I forgot to mention. I found a workaround, you can build the `deb` file with `package.sh` with the command `./package.sh debian ubuntu focal`, in the docker image you can find the deb files needed (@danstiner  made a wonderful work with the docker files to compile everything easily).
That was working fine for me for firefox, but not in chromium (no idea why). Both however, a normal yubikey works perfectly.

**Comment by danstiner** [comment]
Ha, yeah I don't document it but that's the script I use to build out packages. You're welcome to use it but most people who build locally are just using `make install` though.

That said, I just published a new build (0.4.1), so there should be a package available for 20.04 focal fossa now.

I tested Firefox/Chrome in a focal install and they both seemed to work, but for some reason Chromium does not. Feel free to open an issue on that, Chromium works on other platforms so something is fishy.

**Comment by ValZapod** [comment]
Horrible. I just get

```
Ign:6 https://packagecloud.io/danstiner/softu2f/ubuntu trusty InRelease
Err:7 https://packagecloud.io/danstiner/softu2f/ubuntu trusty Release
  404  Not Found [IP: 54.215.200.18 443]

```

Maybe it is geolocked?

**Comment by danstiner** [comment]
@ValZapod Horrible is a strong comment.

Ubuntu trusty is old enough I'm not planning to publish a package for it.

**Comment by ValZapod** [comment]
I am using Debian.

**Comment by danstiner** [comment]
Huh, somehow your apt sources are wrong then, those 404 errors were for trusty urls.

I do publish debian package versions: https://packagecloud.io/app/danstiner/softu2f/search?q=&filter=all&dist=debian

**Comment by ValZapod** [comment]
>I do publish debian package versions:

Yep, just used dpkg -i
