### ISSUE TITLE
Consider publishing uhid-sys and uhid-tokio to Crates.io

### ISSUE THREAD

**Issue by chris-ricketts** [danstiner/rust-u2f#35]
Hi,

Would you consider publishing uhid-sys and uhid-tokio to crates.io?

I found them really useful for testing my [keyboard layout](https://github.com/Chris-Ricketts/keyboard-layouts) crate and I'm sure a lot of other people would too. 

Also, for some reason to publish to crates.io all dependencies, including 'dev-dependencies' are required to be in the crates.io registry before the dependent crate can be published itself. 

I understand if you'd rather not have the hassle. If that is the case, would you mind if I created a 'mirror' repository containing uhid-sys and uhid-tokio and published them to crates.io on your behalf? 

No worries if you would not be comfortable with that either, at the end of the day I could just move the tests to their own repo. It'd just be nice to keep it all together if possible.

Cheers.

**Comment by danstiner** [comment]
I built them as separate packages with the intention of publishing to `crates.io`, just never got around to it.

I don't know what is required to get them ready for publishing, but now that I know someone is interested I'll try to take a look. (Though as always a PR would be gladly accepted)

**Comment by Chris-Ricketts** [comment]
Excellent!

It's actually a pretty painless process to publish to `crates.io`.
https://doc.rust-lang.org/cargo/reference/publishing.html

In regards to preparing the crates, I think the only mandatory additions would be to add the `license` metadata field to the `package` section of each crate's `Cargo.toml`.

The time consuming bits are adding doc comments to the public API, from which the doc.rs stuff is generated from. I'll definitely will be able to help out with this and will issue a PR.

**Comment by danstiner** [comment]
Published https://crates.io/crates/uhid-sys and https://crates.io/crates/tokio-linux-uhid, though I would absolutely still take a PR for doc comments! I might get around to adding them myself lately but I figured better to publish first and get documentation later :)

**Comment by chris-ricketts** [comment]
Thanks for publishing Dan! 
I'll close this issue and try to issue a PR with doc comments this week.
