### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by garymoon** [danstiner/rust-u2f#36]
Hi Dan,

This is a really cool project, thank you for publishing it!

I'm sorry for the extremely vague title, but I'm experiencing a lot of strange behavior that doesn't seem to have a common factor. I'm running Ubuntu 18.04 (which also requires a reboot as Xenial does) and am experiencing the following:

## Chromium
**webauthn.bin.coffee** works great.
**demo.yubico.com/webauthn-technical** works great.
**github.com** shows timeout after two seconds or so, and the journal has suppressed over two thousand lines of output.

## Firefox
**webauthn.bin.coffee** shows aborted after selecting either approve or deny
**demo.yubico.com/webauthn-technical** shows aborted after selecting either approve or deny
**github.com** if a registration attempt follows using either of the above sites, the user-daemon crashes. If it preceeds it, there is no prompt and "This device cannot be registered." is displayed on Github.

For the user-daemon crash I enabled backtracing and got the following:
```
thread 'main' panicked at 'assertion failed: bytes.len() <= MAX_KEY_HANDLE_LEN', /app/u2f-core/src/key_handle.rs:16:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:227
             at src/libstd/panicking.rs:491
   3: std::panicking::begin_panic
   4: <u2fhid_protocol::protocol_state_machine::StateMachine<S>>::accept_packet
   5: <u2fhid_protocol::U2FHID<T, S> as futures::future::Future>::poll
   6: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
   7: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
   8: softu2f_user_daemon::main
   9: std::rt::lang_start::{{closure}}
  10: main
  11: __libc_start_main
  12: _start
```

I'd be happy to provide more complete logs if you'd like them, just let me know which scenarios you want to see them for, and where to store them if you have a preference.

Thanks Dan!

**Comment by danstiner** [comment]
That is indeed strange behavior! Thanks for the thorough report.

It was fun to look at this and see past me has already solved the mystery:
```
/// Spec says 255 is max length, but the provided .C header says 128
/// Chose the smaller, it is still sufficient entropy to avoid collisions
pub(crate) const MAX_KEY_HANDLE_LEN: usize = 128;
```

In retrospect I should have trusted the specification over what a particular implementation choose to do (https://github.com/Yubico/libu2f-host chose a 128 byte max).

I'll bump that up and try to publish a new version soon, hopefully fixing this!

**Comment by danstiner** [comment]
New packages pushed, let me know if that fixed the issue!

**Comment by garymoon** [comment]
Hi Dan,

Thanks so much! Your thinking was spot-on. The user daemon no longer crashes, and I'm able to successfully register on all three sites in Chromium.

I did end up reinstalling all the softu2f packages to get it working, updating softu2f alone didn't pull in the updated dependencies.

It's also still not working at all in Firefox, but I'll open a separate ticket for that.

Thanks again!

Gary.

**Comment by danstiner** [comment]
Great! I'll try to take a look at the packaging some time, maybe something can be improved there.
