### ISSUE TITLE
Does not work on Arch Linux (2)

### ISSUE THREAD

**Issue by terrence-h1974** [danstiner/rust-u2f#37]
I am using Parabola GNU/Linux-libre which is based on Arch Linux and I have the same issue as in #32.
I have set RUST_BACKTRACE=1, here is the result: https://termbin.com/51qp
On https://demo.yubico.com/playground, if I enable Passwordless, it does not crash, nor work.

**Comment by terrence-h1974** [comment]
RUST_BACKTRACE=full http://termbin.com/6cxk

**Comment by danstiner** [comment]
Thanks for the report. I think there are a couple different issues here.

First, this program currently requires desktop notification support compatible with libnotify. You should be able to test you have such support with the [notify-send](https://ss64.com/bash/notify-send.html) program. I don't know your particular distro but the following wiki page from Arch may be useful: https://wiki.archlinux.org/index.php/Desktop_notifications

Second, this program does  *not* support passwordless login. That is part of the new Webauthn specification that was not finalized when I wrote this program. It should work as a normal security key on the playground (together with a password).

**Comment by danstiner** [comment]
Also those logs seem to be debug logs which include raw payload data representing a U2F challenge (Logs from a release build would not include that data). While that should not reveal your secret keys, I would not recommend posting such data on the internet. Probably I should just remove those log statements entirely at this point.

**Comment by terrence-h1974** [comment]
It works!

**Comment by danstiner** [comment]
Nice! I'm glad it's working for you. For my reference, were you just missing a notification server? Would be good to know what kind of dependencies to list if I ever get around to packaging this for Arch.

**Comment by andy-dicki** [comment]
Looks like yes.
