### ISSUE TITLE
Unknown permissions (README.md)

### ISSUE THREAD

**Issue by ghost** [danstiner/rust-u2f#40]
I am not sure which permissions are required for softu2f to work.
By default, it does not work. If I use hack-linux-for-v2f from concise/v2f.py on GitHub, it works.

**Comment by danstiner** [comment]
I would recommend installing https://aur.archlinux.org/packages/u2f-hidraw-policy/ instead.

I would be happy to publish Arch packages if you could contribute a build script for Arch, preferably in the form of a dockerfile similar to the Dockerfiles currently in the root of this repository that I use to build packages for publishing.

**Comment by terrence-h1974** [comment]
Arch Linux does not support SELinux by default. Also, I was unable to find required Makefile in AUR.
I have disabled it by commenting SELinux strings in Makefile (install and uninstall cases).

**Comment by danstiner** [comment]
I'm not sure what you mean, SELinux should be a completely optional thing that is unrelated to the need for your user account to have access to /dev/hidraw* devices.

Also your account seems to have been deleted so I'm going to close this.
