### ISSUE TITLE
Direct attestation failure

### ISSUE THREAD

**Issue by terrence-h1974** [danstiner/rust-u2f#41]
On https://webauthn.bin.coffee/ when using Direct attestation (FIDO-U2F) and pressing "Create Credential" I see the following output: http://termbin.com/6siw
When I press "Get Assertion", I see https://termbin.com/fb7t

**Comment by danstiner** [comment]
I'm not sure what's going wrong on that site, it is falling back to U2F protocol and I can see a valid registration response. I'm not going to dig further into why it's not working given that is a self-labeled "work in progress" site.

**Comment by terrence-h1974** [comment]
Tried it on https://webauthn.io/ and it worked. Looks like the website is bugged.
