### ISSUE TITLE
Implement over USB/IP?

### ISSUE THREAD

**Issue by KOLANICH** [danstiner/rust-u2f#46]
USB/IP is the way to attach "remote" USB devices to a local PC.

The project provides drivers for several OSes, like Linux and Windows. It may make sense to use their drivers instead of own ones and create only a server sitting on 127.0.0.1

**Comment by danstiner** [comment]
It's an interesting idea for getting Windows support, last time I looked the biggest problem was lack of appropriate signing for their kernel driver.

On Linux there is already a virtual HID driver I am using that abstracts away the details of USB to a degree and is probably a simpler approach than USB/IP

**Comment by danstiner** [comment]
Closing, it's an interesting idea but not one I'm planning to pursue anytime soon.

**Comment by KOLANICH** [comment]
@danstiner, https://github.com/xairy/raw-gadget

**Comment by danstiner** [comment]
That definitely looks interesting, I also saw this article about combining the gadget driver with TPM support: https://blog.hansenpartnership.com/webauthn-in-linux-with-a-tpm-via-the-hid-gadget/

Both would be amazing but I'm not going to dig into it this weekend at least :)
