### ISSUE TITLE
Store private key in inaccessible directory

### ISSUE THREAD

**Issue by andy-dicki** [danstiner/rust-u2f#47]
Like U2F device does not allow to extract private key, SoftU2F may use some inaccessible directory (for user, e.g. /root) to prevent malware from stealing keys.

**Comment by danstiner** [comment]
Interesting idea. Technically it is possible, but I think it buys less security than it might seem at first.

- user presence tests would still be done in the user's session, so malware could still login as often as it liked and secretly approve them
- it adds complexity. Currently the code running as root is very minimal, it just forwards HID packets to the userspace service that does all the hard work
- it lowers security against other threat models. Encrypting your user directory or home partition is common, but storing secret keys somewhere else defeats that encryption

I would be open to a PR for this if it could be done cleanly but it's not something I plan to pursue.

**Comment by danstiner** [comment]
Closing, while it's an interesting idea it is not something I'm planning to implement for the above reasons.
