### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by andy-dicki** [danstiner/rust-u2f#51]
If [Solo](https://github.com/solokeys/solo) will merge [this](https://github.com/solokeys/solo/pull/131) pull request and resolve [this](https://github.com/solokeys/solo/issues/134) issue, then rust-u2f may be deprecated, as U2F is legacy protocol (but it is supported by Solo keys).
I'd recommend putting warning in README.md unless there will be FIDO2 support (then rename it to rust-fido)

**Comment by danstiner** [comment]
That's great, Conor et al are doing great work. I would definitely support a solution based on their work.

I'll consider adding a note to the README about FIDO2 if there isn't already.

**Comment by danstiner** [comment]
Updated the README with a note, so I'm going to close this issue.

Also looking at Solo, they do not intend to "develop/support a virtual/software authenticator" even if technically their codebase could be used as a starting point for one.
