### ISSUE TITLE
Install virtual U2F from source

### ISSUE THREAD

**Issue by oleiba** [danstiner/rust-u2f#60]
From the README it seems that the way to install the virtual U2F device, is using apt package i.e. softu2f.

How can one install it from source, i.e. by cloning this repository?
I'm asking because I'm interested in forking and modifying the source code...

**Comment by danstiner** [comment]
There is a Makefile that should work on Fedora, it might also work on Ubuntu but I haven't tested it recently: https://github.com/danstiner/rust-u2f/blob/master/linux/Makefile.

I'm definitely open to contributions (including updated instructions on how to build the project!), but I am curious what kind of modifications you were looking to make.

**Comment by danstiner** [comment]
Added a note to the readme to address this, thanks.
