### ISSUE TITLE
Not work on KDE?

### ISSUE THREAD

**Issue by acomagu** [danstiner/rust-u2f#63]
Hi, Thank you for interesting project!

I'm struggling to work softu2f on Manjaro KDE Edition(KDE on Arch Linux).

You mentioned about KDE at https://github.com/danstiner/rust-u2f/issues/61#issuecomment-539813090 .

KDE is not supported currently, it is?

`notify-send` is working.

```
$ uname -a
Linux acm-manjaro 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019 x86_64 GNU/Linux
```

```
$ systemctl --user status softu2f
● softu2f.service - Software-only U2F Emulation Service
   Loaded: loaded (/etc/systemd/user/softu2f.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-10-29 11:04:40 JST; 25min ago
 Main PID: 1211 (user-daemon)
   CGroup: /user.slice/user-1000.slice/user@1000.service/softu2f.service
           └─1211 /usr/libexec/softu2f/user-daemon

10月 29 11:04:40 acm-manjaro user-daemon[1211]: Oct 29 11:04:40.851 INFO Starting software Universal 2nd Factor device user daemon, version: 0.4.0
10月 29 11:04:40 acm-manjaro user-daemon[1211]: Oct 29 11:04:40.860 DEBG Opening socket, path: /run/softu2f/softu2f.sock
10月 29 11:04:40 acm-manjaro user-daemon[1211]: Oct 29 11:04:40.861 DEBG Sending create device request, request: CreateDeviceRequest
10月 29 11:04:40 acm-manjaro systemd[1201]: Started Software-only U2F Emulation Service.
10月 29 11:04:41 acm-manjaro user-daemon[1211]: Oct 29 11:04:41.228 INFO Loaded configuration file, path: /home/yuki/.config/rustu2f/config.json
10月 29 11:04:41 acm-manjaro user-daemon[1211]: Oct 29 11:04:41.228 WARN Storing secrets in an unencrypted file, dir: /home/yuki/.local/share/rustu2f
10月 29 11:04:41 acm-manjaro user-daemon[1211]: Oct 29 11:04:41.228 INFO Virtual U2F device created, device_id: 1RX9i5Ux6C6WtjI9Mh1_U
10月 29 11:04:41 acm-manjaro user-daemon[1211]: Oct 29 11:04:41.228 TRCE Poll U2FHID
```

No procedure from here:

![Screenshot_20191029_113202](https://user-images.githubusercontent.com/1362750/67732809-f150d180-fa3f-11e9-98b1-983fabb4a5b7.png)

<details><summary>PKGBUILD</summary>

```
pkgname=softu2f-git
pkgver=r241.51bfaa1
pkgrel=1
arch=('i686' 'x86_64')
url="https://github.com/danstiner/rust-u2f"
depends=()
makedepends=('rust' 'git' 'clang')
source=("git+git://github.com/danstiner/rust-u2f")
sha1sums=('SKIP')

pkgver() {
    cd "$srcdir/rust-u2f"
    ( set -o pipefail
      git describe --long 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
      printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
    )
}

build() {
    cd "$srcdir/rust-u2f/linux"
    make build
}

package() {
    cd "$srcdir/rust-u2f/linux"

    mkdir -p "$pkgdir/usr/libexec/softu2f"
    install -Dm 755 target/debug/softu2f-system-daemon "$pkgdir/usr/libexec/softu2f/system-daemon"
    install -Dm 644 system-daemon/softu2f.service "$pkgdir/etc/systemd/system/softu2f.service"
    install -Dm 644 system-daemon/softu2f.socket "$pkgdir/etc/systemd/system/softu2f.socket"
    install -Dm 644 system-daemon/softu2f-tmpfiles.conf "$pkgdir/etc/tmpfiles.d/softu2f.conf"
    # system-daemon/selinux-policy/softu2f-system-daemon.sh
    install -Dm 755 target/debug/softu2f-user-daemon "$pkgdir/usr/libexec/softu2f/user-daemon"
    install -Dm 644 user-daemon/softu2f.service "$pkgdir/etc/systemd/user/softu2f.service"
}
```

After running this, I executed the following also:

```
$ sudo systemctl --system enable softu2f.socket
$ sudo systemctl --system start softu2f.socket
$ systemctl --user enable softu2f.service
$ systemctl --user start softu2f.service
```

</details>

**Comment by danstiner** [comment]
Thanks for sharing the pkgbuild, that all looks right.

You could try sharing the output from `systemctl status softu2f` after trying again, but honestly I'm not sure what is happening. It seems Chrome is not seeing the virtual USB device for some reason. I don't know why KDE would have anything to do with that.

**Comment by grawity** [comment]
The default udev rules currently don't seem to recognize the virtual `/dev/hidraw#` devices as belonging to the user's seat, so they remain only accessible by root.

**Comment by acomagu** [comment]
It works after installing `linux/u2f-hidraw-policy`! Thank you @danstiner and @grawity !
I take up your's time because I'm not familiar with udev and Linux devices. I'm sorry.

And I found @grawity is uploaded your PKGBUILD to AUR. I installed it with [u2f-hidraw-policy](https://aur.archlinux.org/packages/u2f-hidraw-policy/) and enabled the services, and it works instantly! I think it's really useful for Arch users. Thanks!
https://aur.archlinux.org/packages/softu2f/
![Screenshot_20191104_222713](https://user-images.githubusercontent.com/1362750/68124259-474adb00-ff52-11e9-8805-7f56160bf3a8.png)

**Comment by danstiner** [comment]
I had a flash of inspiration this morning that this was probably udev related but you've already solved it and published an arch package? Amazing!

Thanks @grawity, I'll try to coordinate releases with you going forward

**Comment by grawity** [comment]
I just checked and it looks like systemd-udevd in v244 will include a [`fido_id` helper](https://github.com/systemd/systemd/commit/d45ee2f31a8358db0accde2e7c81777cedadc3c2) for recognizing security tokens, which works very similarly to u2f-hidraw-policy. So eventually it should solve this problem by default.

**Comment by danstiner** [comment]
I ran into similar issues before, which is why I have a copy of the u2f-hidraw-policy source in this repository that I build a custom package from to workaround the issue.

Great to hear about the systemd change, that will greatly simplify things for newer versions at least!
