### ISSUE TITLE
no U2F device found

### ISSUE THREAD

**Issue by tobwen** [danstiner/rust-u2f#65]
I'm on Debian Buster and installed SoftU2F like told in the README. Anything seems to work, but the virtual device isn't detected from the normal u2f tools.

_systemd says_:
```
softu2f.service - Software-only U2F Emulation Service
   Loaded: loaded (/lib/systemd/system/softu2f.service; static; vendor preset: enabled)
   Active: active (running) since Sat 2020-01-04 21:30:15 UTC; 9min ago
 Main PID: 711 (system-daemon)
    Tasks: 4 (limit: 4915)
   Memory: 2.0M
   CGroup: /system.slice/softu2f.service
           └─711 /usr/libexec/softu2f/system-daemon

Jan 04 21:30:15 velix systemd[1]: Started Software-only U2F Emulation Service.
Jan 04 21:30:15 velix system-daemon[711]: Jan 04 21:30:15.086 INFO starting SoftU2F system daemon, version: 0.4.0
Jan 04 21:30:15 velix system-daemon[711]: Jan 04 21:30:15.087 INFO Creating virtual U2F device, name: SoftU2F Linux (tobwen@velix), device_id: fRD~LdtgowvUcZBelpIXk
```

_dmesg_ says:
```
hid-generic 0003:FFFF:FFFF.0001: hidraw0: USB HID v0.00 Device [SoftU2F Linux (tobwen@velix)] on
```

But when trying _u2f-host_ and other tools, I'm getting this:
```
u2f-host -aregister -o https://velix/u2f_local < foo
error: u2fh_devs_discover (-5): cannot find U2F device
```

DBUS doesn't list the device. I tried with:
```
dbus-send --system --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```

Anyone with an idea?

**Comment by danstiner** [comment]
libu2f-host and the newer libfido2 seem to only discover USB-type devices, the "virtual" devices this tool creates are HID devices but not true USB devices so they are not discovered. (They also will not be listed in D-Bus, that's an entirely different technology)

Possibly this could be solved by switching to a different emulation approach such as a USB gadget driver. I think that would be neat but I'm not sure when I'd have the time to try it.

I will say I tried the newer libfido2 library and it allows passing explicit devices paths, if I passed the appropriate path it did work. Ex. `fido2-cred -M -u -i cred_param /dev/hidraw0 | fido2-cred -V -o cred`

**Comment by tobwen** [comment]
> libu2f-host and the newer libfido2 seem to only discover USB-type devices, the "virtual" devices this tool creates are HID devices but not true USB devices so they are not discovered. (They also will not be listed in D-Bus, that's an entirely different technology)

My normal FIDO U2F key also is detected as HID, but works. So it seems like _libu2f-host_ is using _D-Bus_?

> I will say I tried the newer libfido2 library and it allows passing explicit devices paths, if I passed the appropriate path it did work. Ex. `fido2-cred -M -u -i cred_param /dev/hidraw0 | fido2-cred -V -o cred`

Oh, this seems to be a FIDO2-tool, I thought you're doing FIDO1 only. Let me play with it.

**Comment by danstiner** [comment]
Make sure `/dev/hidraw0` is actually the U2F device, usually for me it ends up as hidraw2 or 3.

Generally logs from the user daemon are more useful: `journalctl --user -u softu2f.service`

libu2f-host uses hidapi which only supports [USB and bluetooth devices](https://github.com/signal11/hidapi/blob/a6a622ffb680c55da0de787ff93b80280498330f/linux/hid.c#L491).

libfido2 uses the better udev enumeration APIs, but has a few lines that depend on USB. Attached a diff that removes those lines, then even `fido2-token -L` seems to work.

```diff
diff --git a/src/hid_linux.c b/src/hid_linux.c
index d0c143f..4b76a23 100644
--- a/src/hid_linux.c
+++ b/src/hid_linux.c
@@ -185,11 +185,8 @@ copy_info(fido_dev_info_t *di, struct udev *udev,
 {
 	const char		*name;
 	const char		*path;
-	const char		*manufacturer;
-	const char		*product;
 	struct udev_device	*dev = NULL;
 	struct udev_device	*hid_parent;
-	struct udev_device	*usb_parent;
 	int			 ok = -1;
 
 	memset(di, 0, sizeof(*di));
@@ -204,20 +201,12 @@ copy_info(fido_dev_info_t *di, struct udev *udev,
 	    "hid", NULL)) == NULL)
 		goto fail;
 
-	if ((usb_parent = udev_device_get_parent_with_subsystem_devtype(dev,
-	    "usb", "usb_device")) == NULL)
-		goto fail;
-
-	if (parse_uevent(hid_parent, &di->vendor_id, &di->product_id) < 0 ||
-	    (manufacturer = udev_device_get_sysattr_value(usb_parent,
-	    "manufacturer")) == NULL ||
-	    (product = udev_device_get_sysattr_value(usb_parent,
-	    "product")) == NULL)
+	if (parse_uevent(hid_parent, &di->vendor_id, &di->product_id))
 		goto fail;
 
 	di->path = strdup(path);
-	di->manufacturer = strdup(manufacturer);
-	di->product = strdup(product);
+	di->manufacturer = strdup("test");
+	di->product = strdup("test");
 
 	if (di->path == NULL ||
 	    di->manufacturer == NULL ||
```

**Comment by tobwen** [comment]
Hmmm...

### journalctl --user -u softu2f.service
```
No journal files were found.
-- No entries --
```

### dmesg | grep hidraw
```
[    2.524763] hidraw: raw HID events driver (C) Jiri Kosina
[    2.529438] hid-generic 0003:FFFF:FFFF.0001: hidraw0: USB HID v0.00 Device [SoftU2F Linux (tobwen@velix)] on
[    7.527632] hid-generic 0003:FFFF:FFFF.0002: hidraw1: USB HID v0.00 Device [SoftU2F Linux (root@velix)] on
```

**Comment by danstiner** [comment]
Very strange. Both that journalctl gave nothing and that you seem to have devices created both under your tobwen account and root

```
$ dmesg | grep hidraw
[81697.179342] hid-generic 0003:FFFF:FFFF.0007: hidraw2: USB HID v0.00 Device [SoftU2F Linux (dan@xps)] on 
```

```
$ systemctl --user status softu2f.service
● softu2f.service - Software-only U2F Emulation Service
   Loaded: loaded (/usr/lib/systemd/user/softu2f.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-01-08 20:25:00 PST; 16s ago
 Main PID: 238209 (user-daemon)
    Tasks: 3 (limit: 18595)
   Memory: 3.2M
      CPU: 39ms
   CGroup: /user.slice/user-1000.slice/user@1000.service/softu2f.service
           └─238209 /usr/libexec/softu2f/user-daemon

Jan 08 20:25:00 xps systemd[1168]: Started Software-only U2F Emulation Service.
Jan 08 20:25:00 xps user-daemon[238209]: Jan 08 20:25:00.890 INFO Starting software Universal 2nd Factor device user >
Jan 08 20:25:00 xps user-daemon[238209]: Jan 08 20:25:00.911 INFO Loaded configuration file, path: /home/dan/.config/>
Jan 08 20:25:00 xps user-daemon[238209]: Jan 08 20:25:00.911 INFO Storing secrets in your keychain using the D-Bus Se>
Jan 08 20:25:00 xps user-daemon[238209]: Jan 08 20:25:00.954 INFO Virtual U2F device created, device_id: vh3EU13VjQVh>
```

**Comment by tobwen** [comment]
Ah, look. This one creates an output!
```
# systemctl --user status softu2f.service
● softu2f.service - Software-only U2F Emulation Service
     Loaded: loaded (/usr/lib/systemd/user/softu2f.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Thu 2020-01-09 04:41:02 UTC; 1min 34s ago
    Process: 736 ExecStart=/usr/libexec/softu2f/user-daemon (code=killed, signal=ABRT)
   Main PID: 736 (code=killed, signal=ABRT)
        CPU: 5ms

Jan 07 00:33:36 velix systemd[725]: Started Software-only U2F Emulation Service.
Jan 07 00:33:36 velix user-daemon[736]: Jan 07 00:33:36.749 INFO Starting software Universal 2nd Factor device user daemon, version: 0.4.0
Jan 07 00:33:36 velix user-daemon[736]: Jan 07 00:33:36.757 INFO Loaded configuration file, path: /root/.config/rustu2f/config.json
Jan 07 00:33:36 velix user-daemon[736]: Jan 07 00:33:36.757 WARN Storing secrets in an unencrypted file, dir: /root/.local/share/rustu2f
Jan 07 00:33:36 velix user-daemon[736]: Jan 07 00:33:36.757 INFO Virtual U2F device created, device_id: oMWTJW45bmvmq1U~RpmGI
Jan 09 04:41:02 velix user-daemon[736]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Dbus(D-Bus error: The name org.freedesktop.Notifications was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)) }', src/libcore/result.rs:999:5
Jan 09 04:41:02 velix user-daemon[736]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Jan 09 04:41:02 velix systemd[725]: softu2f.service: Main process exited, code=killed, status=6/ABRT
Jan 09 04:41:02 velix systemd[725]: softu2f.service: Failed with result 'signal'.
```

I'm on Debian Buster and did you use DEB installer. Building from source didn't work... also _Dockerfile.debian_ seems to be outdated or incomplete :-(

**Comment by danstiner** [comment]
Interesting, are you using the default window manager? If I have a minute I'll spin up a debian instance. The Dockerfile should work, it's what I use to do cross-distro builds for debian/ubuntu (I use Fedora personally)

**Comment by danstiner** [comment]
I just tried on a fresh Debian 10 install and it seemed to work fine under Gnome. I'm guessing you are using a different window manager, if so you'll have to figure out how to get some kind of notification service running under it, currently that's a requirement in order to be able to approve/deny registration requests.

**Comment by tobwen** [comment]
I'm not using a window manager. For the last 12 years, I haven't used one. I'm working on CLI only. That's why I'm interesting in the FIDO tools. Actually, I'm working to get GnuPG working with U2F devices based on this idea: https://duo.com/labs/tech-notes/u2f-key-support-in-openssh

Your tool might be really useful for debugging, since I cannot remote tunnel my USB device :-)

**Comment by tobwen** [comment]
I've built it from source, but it still crashes. So _softu2f_ really needs a windows manager?

**Comment by danstiner** [comment]
CLI only? That's neat!

But yes, currently the code assumes there is a notification daemon running that it can talk too. I would definitely accept a PR to add support for a CLI only mode though!
