### ISSUE TITLE
how can I copy secret key from one computer to another?

### ISSUE THREAD

**Issue by senid231** [danstiner/rust-u2f#68]
I was searching for config and secrets file but no result

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by danstiner** [comment]
The latest release actually stores all secrets in the default GNOME Keyring so there is no file to find!

If you are migrating to a new computer you should be able to copy over your home directory, or just the keyring data if you want: https://askubuntu.com/questions/907425/how-do-i-back-up-and-restore-passwords-and-keys

Screenshot of some of the entries from my keyring:
![Screenshot from 2020-09-23 22-51-31](https://user-images.githubusercontent.com/52513/94106513-1524bf00-fe2b-11ea-856d-fe4e1a18f07d.jpeg)

**Comment by lmarianski** [comment]
Is there a way to make it save to a file? I'd like to store the tokens on an (encrypted) USB drive for a hardware-token like experience

**Comment by danstiner** [comment]
I would highly recommend purchasing a real hardware key instead, a Yubikey or Solo can be had for as little as $20

However if you understand the security tradeoffs, I would accept a PR to add flags for enabling the file based store and setting the path to use. The file based secret store still exists as a fallback for then a user does not use a keyring.

**Comment by senid231** [comment]
Thanks @danstiner .

I've copied `~/.local/share/keyrings` from old computer and it works.
