### ISSUE TITLE
Cannot open uhid-cdev - No such device

### ISSUE THREAD

**Issue by mbledkowski** [danstiner/rust-u2f#91]
**Describe the bug**
Hi, when I try to run softu2f service I get an error.

**Logs**
systemctl --user status softu2f.service
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Cannot open uhid-cdev \"/dev/uhid\": ENODEV: No such device" }', system-daemon/src/device.rs:174:73

**Comment by mbledkowski** [comment]
os     Arch Linux
host   20FMS12P03 ThinkPad T460
kernel 5.18.1-zen1-1-zen

**Comment by danstiner** [comment]
Does your system have the uhid kernel module installed and enabled?

lsmod should list it something like:
```
$ lsmod | grep uhid
uhid                   20480  1
```

As should `modinfo uhid`

If your kernel doesn't have the uhid driver then sorry I can't be of any help, that's a requirement right now.

**Comment by mbledkowski** [comment]
Yes it does, I rebooted my computer and it works now for some reason XD Anyway thanks for the help <3

**Comment by danstiner** [comment]
Glad it's working for you! I made a note to improve uhid detection a bit so this hopefully doesn't happen.
